MODEL:
  NAME: ResNet101
DATASETS:
  TRAIN: ShanghaiTech_B_Train
  Test: ShangehaiTech_B_Test
DATALOADER:
  BATCH_SIZE: 1
  NUM_WORKER: 8
DEVICE:
  CUDA_NUM: [0, 1]
SOLVER:
  OPTIM: "Adam"
  SCHEDULER_FLAG: True
  LEARNING_RATE: 1e-5
  WEIGHT_DECAY: 1e-4
  EPOCH_NUM: 2000
  LEARNING_DECAY: 0.995
LOSS:
  TRAIN_LOSS: "AVGLoss"
  TEST_LOSS: "EnlargeLoss"
TRANSFORM:
  GT_TRANSFORM: "LabelEnlarge"
  BOTH_TRNASFORM: "TransposeFlip"
SAVER:
  PATH: "./exp"