name: crowdcount

channels:
  - anaconda

dependences:
  - python==3.7
  - pytorch
  - pip:
      - setuptools
      - scipy
      - h5py
      - pandas
      - torchvision
      - scikit_image
      - tqdm
      - numpy
      - Pillow
      - skimage
      - PyYAML
